# Generated by Django 3.2.12 on 2022-02-14 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langauge', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_hier_date', models.DateField(default=django.utils.timezone.now)),
                ('project_submit_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('team_member', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=20)),
                ('profile', models.CharField(choices=[('developer', 'DEVELOPER'), ('project_manager', 'PROJECT_MANAGER'), ('bussiness_development', 'BUSSINESS_DEVELOPMENT'), ('qa', 'QA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GitUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.projectinfo')),
                ('project_langauge', models.ManyToManyField(to='temp.Langauge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.userinfo')),
            ],
        ),
    ]
